apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 172.42.42.100
      peer-asn: 64600
      my-asn: 64600
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 126.23.45.1-126.23.45.20
