apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>FRR</title>
    </head>
    <body>

    <h1>FRR is load balancing</h1>
    <p>Metallb + FRR setup.</p>

    </body>
    </html>
